workdir: "~/data/2026_segmentations/encode"

tools:
  chromhmm_jar: "ChromHMM/ChromHMM.jar"
  omnipeak_jar: "omnipeak.jar"
  homer_dir: "homer"
  chromsizes: "ChromHMM/CHROMSIZES/hg38.txt"
  coords_dir: "ChromHMM/COORDS/hg38"
  java_opts: "-mx4000M"
  gencode_gtf: "gencode.v46.basic.annotation.gtf.gz"
  gene_info: "Homo_sapiens.gene_info.gz"

params:
  chromhmm_bin: 200
  omni_bin: 100
  homer_bin: 200
  macs2_bin: 100
  n_states: 15
  genome: "hg38"
  replicates: true        # process per-replicate folders (rep1/rep2) for datasets that have them
  replicates_only: false  # process replicates only if available, without pooling
  homer: false            # run HOMER-based binarization and segmentation
  macs2: false            # run MACS2-based binarization and segmentation
  omnipeak: false         # run OmniPeak-based binarization and segmentation
  match_method: jaccard   # possible options: overlap | jaccard

datasets:

  imr90:
    cell: "IMR90"
    ref_chromhmm: "ENCFF714POQ"   # ChromHMM 15-state reference BED.gz
    rnaseq: "ENCFF014JRQ"         # RNA-seq TSV
    atac: "ENCFF243NTP"           # ATAC-seq peaks BED.gz
    replicates: true
    bams:
      ENCFF021CLP: {mark: H3K4me3,  rep: rep1, control: ENCFF528QYK}
      ENCFF355WLE: {mark: H3K4me3,  rep: rep2, control: ENCFF686YSU}
      ENCFF064XTS: {mark: H3K27ac,  rep: rep1, control: ENCFF686YSU}
      ENCFF827KCG: {mark: H3K27ac,  rep: rep2, control: ENCFF821GNU}
      ENCFF812CWF: {mark: H3K4me1,  rep: rep1, control: ENCFF528QYK}
      ENCFF927WHP: {mark: H3K4me1,  rep: rep2, control: ENCFF686YSU}
      ENCFF197BAZ: {mark: H3K36me3, rep: rep1, control: ENCFF686YSU}
      ENCFF994SJM: {mark: H3K36me3, rep: rep2, control: ENCFF821GNU}
      ENCFF084CZB: {mark: H3K27me3, rep: rep1, control: ENCFF528QYK}
      ENCFF547BFL: {mark: H3K27me3, rep: rep2, control: ENCFF686YSU}
      ENCFF078EHX: {mark: H3K9me3,  rep: rep1, control: ENCFF528QYK}
      ENCFF942QOQ: {mark: H3K9me3,  rep: rep2, control: ENCFF686YSU}

  monocytes:
    cell: "Monocyte"
    ref_chromhmm: "ENCFF227EMB"
    rnaseq: "ENCFF408GAO"
    atac: null
    replicates: true
    bams:
      ENCFF144PKE: {mark: H3K4me3, rep: rep1, control: ENCFF421DXL}
      ENCFF640GCK: {mark: H3K4me3, rep: rep2, control: ENCFF662FMZ}
      ENCFF872QFO: {mark: H3K27ac, rep: rep1, control: ENCFF421DXL}
      ENCFF014BCD: {mark: H3K27ac, rep: rep2, control: ENCFF662FMZ}
      ENCFF141KHX: {mark: H3K4me1, rep: rep1, control: ENCFF421DXL}
      ENCFF573MNS: {mark: H3K4me1, rep: rep2, control: ENCFF662FMZ}
      ENCFF150SGV: {mark: H3K36me3, rep: rep1, control: ENCFF421DXL}
      ENCFF629ODR: {mark: H3K36me3, rep: rep2, control: ENCFF662FMZ}
      ENCFF225KQA: {mark: H3K27me3, control: ENCFF134CHO} # Rep1 only
      ENCFF168UCU: {mark: H3K9me3, rep: rep1, control: ENCFF421DXL}
      ENCFF537BKE: {mark: H3K9me3, rep: rep2, control: ENCFF662FMZ}

  monocytes_mint:
    cell: "MonocyteMint"
    ref_chromhmm: "ENCFF166IHY" # non-standard states naming
    rnaseq: null
    atac: null
    replicates: false
    bams:
      ENCFF600ZLL: {mark: H3K4me3, control: ENCFF041EUP}
      ENCFF438HLV: {mark: H3K27ac, control: ENCFF041EUP}
      ENCFF668OLF: {mark: H3K4me1, control: ENCFF041EUP}
      ENCFF128UWF: {mark: H3K36me3, control: ENCFF041EUP}
      ENCFF507NNO: {mark: H3K27me3, control: ENCFF041EUP}
      ENCFF613TME: {mark: H3K9me3, control: ENCFF041EUP}

  gm12878_mint:
    cell: "GM12878Mint"
    ref_chromhmm: "ENCFF870JAH" # non-standard states naming
    rnaseq: null
    atac: null
    replicates: false
    bams:
      ENCFF641VOI: {mark: H3K4me3, control: ENCFF369DNR}
      ENCFF241BPW: {mark: H3K27ac, control: ENCFF369DNR}
      ENCFF934GLQ: {mark: H3K4me1, control: ENCFF369DNR}
      ENCFF869PBS: {mark: H3K36me3, control: ENCFF369DNR}
      ENCFF304ZNG: {mark: H3K9me3, control: ENCFF369DNR}
      ENCFF545WJH: {mark: H3K27me3, control: ENCFF369DNR}

  spleen:
    cell: "Spleen"
    ref_chromhmm: "ENCFF183AWD"
    rnaseq: "ENCFF143INW"         # total RNA-seq, gene quant TSV (ENCSR096LTX, female adult 61y)
    atac: "ENCFF105FRE"           # ATAC-seq IDR peaks (ENCSR078EBD, female adult 51y)
    replicates: true
    bams:
      ENCFF838OPW: {mark: H3K4me3, rep: rep1, control: ENCFF921FHW}
      ENCFF464ZDR: {mark: H3K4me3, rep: rep2, control: ENCFF125VUN}
      ENCFF185DQS: {mark: H3K27ac, rep: rep1, control: ENCFF921FHW}
      ENCFF472TSV: {mark: H3K27ac, rep: rep2, control: ENCFF125VUN}
      ENCFF915NOI: {mark: H3K4me1, rep: rep1, control: ENCFF921FHW}
      ENCFF702ICJ: {mark: H3K4me1, rep: rep2, control: ENCFF125VUN}
      ENCFF877UDA: {mark: H3K36me3, rep: rep1, control: ENCFF921FHW}
      ENCFF934RMM: {mark: H3K36me3, rep: rep2, control: ENCFF125VUN}
      ENCFF865ORP: {mark: H3K9me3, rep: rep1, control: ENCFF921FHW}
      ENCFF425JOG: {mark: H3K9me3, rep: rep2, control: ENCFF125VUN}
      ENCFF811PTP: {mark: H3K27me3, rep: rep1, control: ENCFF921FHW}
      ENCFF488FJX: {mark: H3K27me3, rep: rep2, control: ENCFF125VUN}
